lunguage: objective-c
  

before_install:
  - gem update
  - gem upgrade
  - gem install cocoapods -r
  - pod setup
  - pod install

script:
  - xctool -workspace TravisTest.xcworkspace -scheme YOURSCHEME -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace TravisTest.xcworkspace -scheme YOURSCHEME -destination 'platform=iOS Simulator,name=iPhone 6' test



