lunguage: objective-c
  
rvm:
  - 2.0.0

before_install:
  - sudo gem update --system
  - gem install cocoapods -r
  - pod setup
  - pod install

script:
  - xctool -workspace TravisTest.xcworkspace -scheme TravisTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace TravisTest.xcworkspace -scheme TravisTest -destination 'platform=iOS Simulator,name=iPhone 6' test



